In [1]:
import pandas as pd
import numpy as np
import time
from datetime import datetime, timedelta

In [3]:
all_data = pd.read_csv("all-data.csv")

In [4]:
target_columns["support-quarantine", "wearing-masks", ""

,Date,yoy reservations %,New Cases,support-quarantine,wearing-masks,avoiding-crowds,% of hospital capacity for covid,# of hospitalisations,% of hospitalizations for covid,# ICU Beds for covid,Total_Reported
0,2020-02-18,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-19,-6.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-20,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-21,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-22,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
236,2020-10-11,-15.81,2262.0,NaN,NaN,NaN,2.20%,93.0,2.90%,30.0,31208.0
237,2020-10-12,-37.19,2384.0,56.0,79.0,65.0,2.20%,91.0,2.90%,32.0,31341.0
238,2020-10-13,-39.68,5050.0,NaN,NaN,NaN,2.30%,96.0,3.10%,34.0,NaN
239,2020-10-14,-39.02,4564.0,NaN,NaN,NaN,2.40%,99.0,3.10%,34.0,31554.0
240,2020-10-15,-33.04,4615.0,NaN,NaN,NaN,2.30%,99.0,3.10%,39.0,31650.0